package com.telegram_bot_animal_shelter.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.*;

import javax.persistence.*;

/**
 * Entity for shelter pet: cat.
 * @author: Kucherenko V.V.
 * @version 0.0.1
 */
@Entity
@Table(name = "cat")
@Getter
@Setter
@EqualsAndHashCode
@ToString
@AllArgsConstructor
@NoArgsConstructor
public class Cat extends Animal {

    /**
     * Autogenerated primary key for entity cat
     * @param id
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    @JsonIgnore
    private Long id;


    public Cat(String name, String breed, int age, String description) {
        super(name, breed, age, description);
    }
}
