package com.telegram_bot_animal_shelter.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.*;

import javax.persistence.*;

/**
 * Entity for shelter pet: dog.
 * @author: Kucherenko V.V.
 * @version 0.0.1
 */

@Entity
@Table(name = "dog")
@Getter
@Setter
@EqualsAndHashCode
@ToString
@AllArgsConstructor
@NoArgsConstructor
public class Dog extends Animal{

    /**
     * Autogenerated primary key for entity dog
     * @param id
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", nullable = false)
    @JsonIgnore
    private Long id;

    public Dog(String name, String breed, int age, String description) {
        super(name, breed, age, description);
    }


}
