package com.telegram_bot_animal_shelter.model;

import lombok.*;

import javax.persistence.*;

/**
 * Entity for shelter pet: dog.
 * @author: Kucherenko V.V.
 * @version 0.0.1
 */

@Entity
@Getter
@Setter
@EqualsAndHashCode
@ToString
@AllArgsConstructor
@NoArgsConstructor
public class Dog{

    /**
     * Autogenerated primary key for entity dog
     * @param id
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Dog name
     * @param name
     */
    @Column(name = "name")
    private String name;

    /**
     * Dog breed. Like: Shepherd, Alabai
     * @param breed
     */
    @Column(name = "breed")
    private String breed;

    /**
     * Dog age
     * @param age
     */
    @Column(name = "age")
    private int age;

    /**
     * Additional information about the pet: habbits, health, features
     * @param description
     */
    @Column(name = "description")
    private String description;

}
