package com.telegram_bot_animal_shelter.model;

import lombok.*;

import javax.persistence.*;

/**
 * Entity for person who wants to give a dog.
 * @author: Kucherenko V.V.
 * @version 0.0.1
 */
@Entity
@Getter
@Setter
@EqualsAndHashCode
@ToString
@AllArgsConstructor
@NoArgsConstructor
public class PersonDog {

    /**
     * Autogenerated primary key id for PersonDog
     * @param id
     */
    @Id
    @GeneratedValue
    private Long id;

    /**
     * PersonDog name
     * @param name
     */
    private String name;

    /**
     * Year of birthday PersonDog
     * @param yearsOfBirth
     */
    private int yearOfBirth;

    /**
     * Phone number PersonDog
     * @param phone
     */
    private String phone;

    /**
     * PersonCat address: City, street, home, flat
     * @address
     */
    private String address;

    /**
     * Parameter for identity chat PersonDog with telegram bot
     * @param chatId
     */
    private Long chatId;

    /**
     * Status of obtaining a pet dog by a person.
     * @see Status
     * @param status
     */
    private Status status;

    /**
     * Connect to entity dog, One person can have One dog
     * @param dog
     */
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "dog_id")
    private Dog dog;
}
