package com.telegram_bot_animal_shelter.model;

import lombok.*;

import javax.persistence.*;

/**
 * Entity for person who wants to give a cat.
 * @author: Kucherenko V.V.
 * @version 0.0.1
 */
@Entity
@Getter
@Setter
@EqualsAndHashCode
@ToString
@AllArgsConstructor
@NoArgsConstructor
public class PersonCat {

    /**
     * Autogenerated primary key id for PersonCat
     * @param id
     */
    @Id
    @GeneratedValue
    private Long id;

    /**
     * PersonCat name
     * @param name
     */
    private String name;

    /**
     * Year of birthday PersonCat
     * @param yearsOfBirth
     */
    private int yearOfBirth;

    /**
     * Phone number PersonCat
     * @param
     */
    private String phone;

    /**
     * PersonCat address: City, street, home, flat
     * @param address
     */
    private String address;

    /**
     * Parameter for identity chat PersonCat with telegram bot
     * @param chatId
     */
    private Long chatId;

    /**
     * Status of obtaining a pet cat by a person.
     * @see Status
     * @param status
     */
    private Status status;

    /**
     * Connect to entity cat, One person can have One cat
     * @param cat
     */
    @OneToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "cat_id")
    private Cat cat;
}
