package com.telegram_bot_animal_shelter.model;

import lombok.*;

import javax.persistence.*;
import java.util.Date;

/**
 * Entity for report about given pet: ration, health, habits, photo, report date.
 * @author: Kucherenko V.V.
 * @version 0.0.1
 */
@Entity
@Getter
@Setter
@EqualsAndHashCode
@ToString
@AllArgsConstructor
@NoArgsConstructor
public class Report {

    /**
     * Autogenerated id for entity Report
     * @param id
     */
    @Id
    @GeneratedValue
    private Long id;

    /**
     * Parameter for connect entity report in telegram bot with person who gives a pet
     * @param chatId
     */
    private Long chatId;

    /**
     * Person send ration his pet
     * @param ration
     */
    private String ration;

    /**
     * Person send information about ration his new pet
     * @parat health
     */
    private String health;

    /**
     * Person send information about habits his pet, getting new ones or rejecting old ones
     * @param habits
     */
    private String habits;

    /**
     * How many days person send a report
     * @param days
     */
    private Long days;

    /**
     * Path for file with photo
     * @param filePath
     */
    private String filePath;

    /**
     * Size of sent file
     * @param fileSize
     */
    private Long fileSize;

    /**
     * Byte array for file transfer
     * @param data
     */
    @Lob
    private byte[] data;

    /**
     * Caption for file
     * @param caption
     */
    private String caption;

    /**
     * Date of lastMessage
     * @param lastMessage
     */
    private Date lastMessage;

    /**
     * Count of last messages
     * @param lastMessageMs
     */
    private Long lastMessageMs;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(referencedColumnName = "id")
    private PersonCat personCat;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(referencedColumnName = "id")
    private PersonDog personDog;
}
